version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run: apt update
      - run: DEBIAN_FRONTEND=noninteractive TZ=Europe/Brussels apt install -y gcc g++ libsfml-dev cmake git
      - run: mkdir -p build
      - run: cd build && cmake ..
      - run: cd build && make
dependencies:
  pre:
    - sudo apt-get install apt -y
    - sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y
    - sudo apt-get update -y; true
    - sudo apt-get install -y qt54webkit libwebkit-dev libgstreamer0.10-dev
    - echo "/opt/qt512/bin/qt512-env.sh" >> ~/.circlerc